"use client";

import React, { useState, useEffect } from "react";
import "katex/dist/katex.min.css";
import { BlockMath } from "react-katex";

interface GaussianQuadratureVisualizerProps {
  initialM?: number;
  initialN?: number;
}

export function GaussianQuadratureVisualizer({
  initialM = 2,
  initialN = 1,
}: GaussianQuadratureVisualizerProps = {}) {
  const [m, setM] = useState<number>(initialM);
  const [n, setN] = useState<number>(initialN);

  useEffect(() => {
    setM(initialM);
    setN(initialN);
  }, [initialM, initialN]);

  const a = Math.abs(m * m - n * n);
  const b = Math.abs(2 * m * n);
  const c = m * m + n * n;

  // Scale for rendering SVG
  const maxVal = Math.max(m, n, a, b, c) * 1.2;
  const scale = 200 / maxVal;

  return (
    <div className="my-8 p-6 bg-zinc-950 border border-zinc-800 rounded-2xl shadow-2xl font-sans">
      <div className="mb-6">
        <h3 className="text-emerald-400 font-bold text-lg">Gaussian Quadrature & Pythagorean Triples</h3>
        <p className="text-zinc-400 text-sm">Every primitive Pythagorean triple is generated by squaring a Gaussian integer.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Controls and Math */}
        <div className="flex flex-col gap-6">
          <div className="flex gap-4 items-center bg-zinc-900/50 p-4 rounded-xl border border-zinc-800/50">
            <div className="flex-1">
              <label className="text-xs text-zinc-500 font-bold uppercase mb-2 block">Seed m (Real)</label>
              <input 
                type="range" min="1" max="10" value={m} 
                onChange={(e) => setM(parseInt(e.target.value))}
                className="w-full accent-amber-500"
              />
              <div className="text-center font-mono text-amber-500 mt-1">{m}</div>
            </div>
            <div className="flex-1">
              <label className="text-xs text-zinc-500 font-bold uppercase mb-2 block">Seed n (Imaginary)</label>
              <input 
                type="range" min="1" max="10" value={n} 
                onChange={(e) => setN(parseInt(e.target.value))}
                className="w-full accent-amber-500"
              />
              <div className="text-center font-mono text-amber-500 mt-1">{n}</div>
            </div>
          </div>

          <div className="p-4 bg-zinc-900/50 rounded-xl border border-zinc-800/50 overflow-x-auto scrollbar-none">
            <BlockMath math={`z = \\textcolor{#fbbf24}{${m}} + \\textcolor{#fbbf24}{${n}}i`} />
            <BlockMath math={`z^2 = (\\textcolor{#fbbf24}{${m}}^2 - \\textcolor{#fbbf24}{${n}}^2) + 2(\\textcolor{#fbbf24}{${m}})(\\textcolor{#fbbf24}{${n}})i`} />
            <BlockMath math={`z^2 = \\textcolor{#10b981}{${a}} + \\textcolor{#3b82f6}{${b}}i`} />
          </div>

          <div className="p-4 bg-zinc-900/50 rounded-xl border border-zinc-800/50 overflow-x-auto scrollbar-none text-center">
            <BlockMath math={`\\textcolor{#10b981}{a}^2 + \\textcolor{#3b82f6}{b}^2 = \\textcolor{#f43f5e}{c}^2`} />
            <BlockMath math={`\\textcolor{#10b981}{${a}}^2 + \\textcolor{#3b82f6}{${b}}^2 = \\textcolor{#f43f5e}{${c}}^2`} />
            <BlockMath math={`\\textcolor{#10b981}{${a * a}} + \\textcolor{#3b82f6}{${b * b}} = \\textcolor{#f43f5e}{${c * c}}`} />
          </div>
        </div>

        {/* Visual Plane */}
        <div className="relative aspect-square bg-zinc-900/50 rounded-xl border border-zinc-800/50 overflow-hidden flex items-center justify-center">
          <svg viewBox="0 0 220 220" className="w-full h-full p-4 overflow-visible">
            <g transform="translate(10, 210) scale(1, -1)">
              {/* Axes */}
              <line x1="0" y1="0" x2="200" y2="0" stroke="#3f3f46" strokeWidth="1" />
              <line x1="0" y1="0" x2="0" y2="200" stroke="#3f3f46" strokeWidth="1" />
              
              {/* z vector */}
              <line x1="0" y1="0" x2={m * scale} y2={n * scale} stroke="#fbbf24" strokeWidth="2" strokeDasharray="4 4" />
              <circle cx={m * scale} cy={n * scale} r="4" fill="#fbbf24" />
              <text x={m * scale + 5} y={-n * scale - 5} fill="#fbbf24" fontSize="12" transform="scale(1, -1)" fontWeight="bold">z</text>
              
              {/* z^2 / Pythagorean Triangle */}
              <polygon points={`0,0 ${a * scale},0 ${a * scale},${b * scale}`} fill="#10b981" fillOpacity="0.1" stroke="none" />
              
              <line x1="0" y1="0" x2={a * scale} y2="0" stroke="#10b981" strokeWidth="3" />
              <line x1={a * scale} y1="0" x2={a * scale} y2={b * scale} stroke="#3b82f6" strokeWidth="3" />
              <line x1="0" y1="0" x2={a * scale} y2={b * scale} stroke="#f43f5e" strokeWidth="3" />
              
              <circle cx={a * scale} cy={b * scale} r="5" fill="#f43f5e" />
              <text x={a * scale + 8} y={-b * scale - 8} fill="#f43f5e" fontSize="14" transform="scale(1, -1)" fontWeight="bold">z²</text>
              
              <text x={(a * scale) / 2} y={15} fill="#10b981" fontSize="14" transform="scale(1, -1)" fontWeight="bold">a</text>
              <text x={a * scale + 8} y={-(b * scale) / 2} fill="#3b82f6" fontSize="14" transform="scale(1, -1)" fontWeight="bold">b</text>
            </g>
          </svg>
        </div>
      </div>
    </div>
  );
}
